// Problem 1 Solution
/* If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000.*/
var sum = 0;
for (var i = 0; i < 1000; i++)
{
    if (i % 3 === 0)
    {
        sum += i;
    }
    else if (i % 5 === 0)
    {
        sum += i;
    }    
}
console.log(sum);

// Problem 2 Solution
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
   z = current" fib sequence number
   x =  "old" fib sequence number
   y = "oldest" fib sequence number
*/
var x = 0;
var y = 0;
var z = 1;
var sum = 0;

for (x = 0; z < 4000000; z = x + y )
{
    if (z % 2 === 0)
    {
        sum += z;
    }
    y = x;
    x = z;
}
console.log("The sum of the even valued terms in the Fibonacci sequence is: " + sum);

// Problem 3 Solution
/*
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?
*/
function IsItPrime(test)
{
    if (test === 2 || test === 3 || test === 5 || test === 7)
    {
    return true;
    }
    else if (test === 1)
    {
    return false;
    }
    else if (test % 2 === 0 || test % 3 === 0 || test % 5 === 0 || test % 7 === 0 )
    {
    return false;
    }
    else if (test % test === 0 || test % 1 === 0)
    {
    return true;     
    }
    else
    {
    return false;
    }
}

var n = 13195;
var primeFactor = [];
for (i=1; i <= n; i++)
{
    if (IsItPrime(i))
    {
        if(n % i === 0)
        {
            primeFactor.push(i);
        }
    }
}
var number = 0;
console.log(primeFactor);
number = primeFactor[0];
console.log(number);
var z = 0;
var x = 0;
var which = 0;
for (i = 0; z < n; i++)
{
    if(i===0)
    {
        z = primeFactor[i] * primeFactor[i + 1];
        console.log(z);
        which = i + 1;
    }
    else if(i>0)
    {
        x = z * primeFactor[i + 1];
        console.log(x);
        z = x;
        which = which + 1;
    }
}
console.log(z);
var LargePrime = 0;
LargePrime = primeFactor[which];
console.log(LargePrime);
